### ISSUE TITLE
求助热线不如这本书好用

### ISSUE THREAD

**Issue by ghost** [YuriMiller/CompleteSuicideManual-Zh_CN#38]
每次打求助热线或者找心理咨询师，他们总会把一半以上的时间拿去问你，有没有自杀想法，有没有准备工具，有没有危险的东西在身边。

他们的目的不是帮助你解决问题，只是完成不让你死的目的。但是根源不除去，你一直就会想死。我讨厌这种自诩为能帮助你的东西。

这本书下载下来，阅读，已经很久了。

每个人都看似很关心你，说什么会好起来的。其实他们只是不让你死，让你继续受苦而已。不让人自杀是一种潜意识，不是真正思考过的行为。也许几百年后，自杀就被人类接纳了。

**Comment by LearnProgra** [comment]
兄弟，愛惜生命，我只能這麼說。

我不清楚你具體的情況，沒法給出建議。

想死當然很簡單，很逃避人間；但是想活不容易，是個有趣的挑戰，你不覺得嗎？

把自己「救活」吧。

**Comment by liyiping1016** [comment]
Agree, knowing there is always method wo pain makes me feel relieved , meanwhile some of these cases are indeed horrible to me TT.  I might try someday but not today. Hope no one would notice my comment hhh

**Comment by ethushiroha** [comment]
> De acuerdo, saber que siempre hay un método para que el dolor me haga sentir aliviado, mientras tanto algunos de estos casos son realmente horribles para mí TT. Podría intentarlo algún día, pero no hoy. Espero que nadie se dé cuenta de mi comentario HHH

I find you. Aha
